# Generated by Django 4.2.2 on 2023-07-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_sellstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellstatus',
            name='status',
            field=models.CharField(choices=[('P', 'payed'), ('S', 'sended')], default='P', max_length=1),
        ),
    ]
