# Generated by Django 4.2.2 on 2023-06-30 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_productvariation_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='product_owner',
        ),
        migrations.AddField(
            model_name='product',
            name='product_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
